### ISSUE TITLE
Non-Ideal Wires Causing Errors

### ISSUE THREAD

**Issue by Krb686** [hausen/circuit-simulator#3]
Unfortunately I think the sections of code written to use realistic wires are still causing quite a few errors.  

I noticed this problem when one of my circuits ran fine on Falstad's original, but yet fails to converge in this version.  Setting the boolean ideal to true inside WireElm allows the circuit to run properly on this version.

Rather difficult to debug, but so far I have traced the error to the program attempting to set one of the nodes to a voltage of 2.6 billion volts.

![hausen_error_1](https://cloud.githubusercontent.com/assets/959619/3013711/fe4a95f6-df4c-11e3-9440-9d67dd688588.png)

The value of 2.6 billion volts is inserted into the array called "volts".  Inside of MosfetElm, this causes execution to run inside one of these if-statements, replacing the value with lastv2 + 0.5.

![hausen_error_2](https://cloud.githubusercontent.com/assets/959619/3013927/10d1923e-df51-11e3-8f6c-e271ec3944e8.png)

After that, the convergence is set to false, here:

![hausen_error_3](https://cloud.githubusercontent.com/assets/959619/3013932/249b3c20-df51-11e3-893f-b160a30902e0.png)

This repeats until it has looped the maximum of 5,000 times, where it then fails.  Each time the large value of 2.6 billion alternates between being in volts[1] or volts[2]

Now trying to trace this backwards, that result of 2.6 Billion is computed inside lu_solve in the matrix called b.  Harder to trace at this point because I don't know which value is incorrect.

It comes from the statement:

b[i] = tot / a[i][i]

tot = -2.6*10^21

![hausen_error_4](https://cloud.githubusercontent.com/assets/959619/3014007/257e590a-df52-11e3-801d-b5f0f26f584a.png)

And a[i][i] = -1*10^12, (in this case i=29)

![hausen_error_5](https://cloud.githubusercontent.com/assets/959619/3014018/60a7c8a4-df52-11e3-8734-ff87a8623577.png)

This may or may not be of any help.  At this point it becomes much harder because this is getting into all of the matrix calculations

**Comment by hausen** [comment]
After more than 2 years, I realized that the default wire resistance was too low. I have increased it from 1pΩ to 1µΩ. It may not fix the problem entirely, but this seems to be an issue with the original simulation algorithm; if you use Paul Falstad's original version and replace the wires with 1pΩ resistors, you'll get the same error.
