### ISSUE TITLE
No Draw menu on Java applet and Java application versions of simulator

### ISSUE THREAD

**Issue by jrao** [hausen/circuit-simulator#5]
There is no Draw menu on the Java applet and Java application versions of the simulator. Is this a bug? If not, how can you add new circuit elements to a blank (or any other) circuit?

**Comment by jrao** [comment]
A workaround is to use the JavaScript version here (http://www.falstad.com/circuit/) to create new circuits, export them and import them into the Java application.

**Comment by sharpie7** [comment]
Right click on the diagram to open the draw menu.

**Comment by jrao** [comment]
Perfect, thank you.
