### ISSUE TITLE
Doesn't seem to work in macOS

### ISSUE THREAD

**Issue by SirClickALot** [hausen/circuit-simulator#7]
I have downloaded the last .dmg and tried it on my MacBook Pro ....

  Model Name:	MacBook Pro
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  OS: Big Sur 11.5.2

The nwjs.app just doesn't open any windows when run.

Any guidance anyone?
![2021-09-13_19-47-37](https://user-images.githubusercontent.com/1190521/133139764-8acb0c5d-0ee9-46cb-bac3-5aaec7c7ac36.png)

**Comment by pfalstad** [comment]
Which .dmg did you download?  It's not called nwjs.app and that's not the right icon.  The correct one is here: http://www.falstad.com/circuit/offline/

**Comment by pfalstad** [comment]
Whoops this isn't my repo!  Sorry about that.

**Comment by SirClickALot** [comment]
I realised that too but all sorted now because I downloaded the one you
sent me to and it all works fine Paul. This is absolutely exceptional work:
exactly what I have been looking for in amongst a plethora of offerings out
there.

Thank you

Nick Abbott

**Comment by hausen** [comment]
Thanks for providing free support to downstream repos, @pfalstad . 😀
